"""Create Message table

Revision ID: 5837dceeb57a
Revises: fea58d3a339c
Create Date: 2025-06-03 12:56:04.802873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5837dceeb57a'
down_revision: Union[str, None] = 'fea58d3a339c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('from_number', sa.String(length=20), nullable=False),
    sa.Column('to_number', sa.String(length=20), nullable=False),
    sa.Column('message_type', sa.Enum('text', 'image', 'video', 'audio', 'document', 'location', 'contacts', 'sticker', 'reaction', 'system', name='message_type_enum'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='message_direction_enum'), nullable=False),
    sa.Column('status', sa.Enum('sent', 'delivered', 'read', 'failed', name='message_status_enum'), server_default='sent', nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
